### ISSUE TITLE
"AttributeError: module '__main__' has no attribute '__file__'. Did you mean: '__name__'?"

### ISSUE THREAD

**Issue by EvgenyKV** [Jaded-Encoding-Thaumaturgy/vs-tools#127]
https://aur.archlinux.org/packages/vapoursynth-plugin-vstools-git

```
Failed to evaluate the script:
Python exception: module '__main__' has no attribute '__file__'

Traceback (most recent call last):
File "src/cython/vapoursynth.pyx", line 3374, in vapoursynth._vpy_evaluate
File "src/cython/vapoursynth.pyx", line 3375, in vapoursynth._vpy_evaluate
File "/tmp/1/script.vpy", line 3, in 
import havsfunc as haf
File "/usr/lib/python3.12/site-packages/havsfunc/__init__.py", line 1, in 
from .havsfunc import *
File "/usr/lib/python3.12/site-packages/havsfunc/havsfunc.py", line 8, in 
from vsdenoise import BM3D, nl_means, prefilter_to_full_range
File "/usr/lib/python3.12/site-packages/vsdenoise/__init__.py", line 2, in 
from .blockmatch import *
File "/usr/lib/python3.12/site-packages/vsdenoise/blockmatch.py", line 5, in 
from vsexprtools import norm_expr
File "/usr/lib/python3.12/site-packages/vsexprtools/__init__.py", line 1, in 
from .exprop import * # noqa: F401, F403
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/vsexprtools/exprop.py", line 7, in 
from vstools import (
File "/usr/lib/python3.12/site-packages/vstools/__init__.py", line 3, in 
from .functions import * # noqa: F401, F403
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/vstools/functions/__init__.py", line 9, in 
from .timecodes import * # noqa: F401, F403
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/vstools/functions/timecodes.py", line 23, in 
keyframes_storage = PackageStorage(package_name='keyframes')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/vstools/functions/file.py", line 34, in __init__
cwd = SPath(get_script_path())
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/stgpytools/utils/file.py", line 46, in get_script_path
return SPath(__main__.__file__)
^^^^^^^^^^^^^^^^^
AttributeError: module '__main__' has no attribute '__file__'. Did you mean: '__name__'?
```

**Comment by srappan** [comment]
You probably need stgpytools latest
